### PR TITLE
Update International Plates

### PR DESCRIPTION
**Pull request by glyh0515**

### CODE REVIEW

**Comment by myjian** [comment]
can you update public/data/plate-info/intl0-12.json and public/data/plate-info/intl12.json too?

**Comment by glyh0515** [comment]
Yeah I'm updating now. Just to confirm, 前前前世 is not included for International 堇 and 舞 plates?

**Comment by Mantou1233** [comment]
yes

**Comment by myjian** [comment]
If I remember correctly, 前前前世 is not included in any plates

**Review by myjian — APPROVED** [review]

**Pull request merged**
