### PR TITLE
Update intl0-1.json

### PR DESCRIPTION
**Pull request by glyh0515**
Remove ジングルベル for International maimai ~ maimai PLUS

### CODE REVIEW

**Comment by myjian** [comment]
not sure why you closed the pull request, but the change looks good to me. I've applied the change in 660f7ff30b794c3667b553ec8d052d6e252daf2d. Thank you for the contribution!

**Comment by glyh0515** [comment]
Not familiar with Github so I am still exploring. Also for the removed songs on 2024/09/13, the name plates' progress is not yet updated.

**Comment by glyh0515** [comment]
Not familiar with Github so I am still exploring. Also for the removed songs on 2024/09/13, the name plates' progress is not yet updated.

**Comment by glyh0515** [comment]
Let me open a new pull request for further discussion.

**Pull request closed without merging**
